### ISSUE TITLE
What license is this released under?

### ISSUE THREAD

**Issue by ukBaz** [GeekyTim/Open-Smart-RGB-LED-Strip-Driver-for-Raspberry-Pi#1]
You might want to take a look at:

https://help.github.com/articles/licensing-a-repository/

> Without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

**Comment by GeekyTim** [comment]
Thanks - didn't realise that bit hadn't been done!
